---
title: "Curso CIFO 2024"
format: html
---

## VIRTUALBOX de Oracle

### Instalar una Virtual Machine:

-   Need 250 Gb
-   Download .ISO (ej. Linux Mint 21.2)
-   Create new machine\> name, ubicacion SSD, iso
-   mini 20Gb de RAM, 4 cpu, disco duro 250Gb
-   Install with Codecs privados (para imagenes, videos ; interpreta los .jpg)
-   Install Gaest Additions (para varias pantallas & cie)

## LINUX

### BASH
-   lenguaje de programacion de Linux (ej. \$sudo)
-   puede buscar dentro de los ficheros
$ ./name.sh : para ejecutar una aplicacion en terminal
$ sudo apt-get install <name> : para instalar aplicaciones
$ quarto --version


## QUARTO

Instalar 1 Virtual Machine:

## SCRUM
-   Planificar
-   Ejecutar
-   Revisar
-   Reflexionar (Retro)(Feedback)

## UML


## JAVA
-   ?SE vs EE: Basic vs Para hacer Webs? 
### Install JDK
-   $ sudo update-java-alternatives --list : para ver los jdks instalados
-   $ sudo apt-get install openjdk-17-jdk 

### MOOC

## GIT/GITHUB


## MINDSET
### Aprendizaje
-   picnic - aprox - superficial
-   aprofundizar - mecanismo
-   consolidar - documentar
### Energy
-   problema Simple (step by step)
-   problema Complicado (replicable)
-   Problema Complejo (a medida)

## Arquitectura
### modelo MVC 
Model-View-Controller(server)
### de clase
FRONT(React)--(APIRest)--SERVER(Springboot)--(JPA)--DBs(SQL, no SQL, cloud)
### ROS/ROC
ROS: html se genefra en el Server, no hay APIRest
ROC: html se genera en el Client via APIRest

## Vocabulario
-   IDE: application/programa (ej. Idea)
-   DevOps: equipo de deployment
-   Maven: gestor de libraries/paquetes
-   FullStack: server, debil pero completo
-   server = pc conectado
-   SPA: Simple Page Application 
-   MPA: Multiple Pages Application?
-   ROS: Render On Server
-   ROC: Render on Client
